assemblytest: assemblytest.c

	gcc -static -o assemblytest assemblytest.c

cdpassembly: cdpassembly.c

	gcc -static -o cdpassembly cdpassembly.c

mcrassembly: mcrassembly.c

	gcc -static -o mcrassembly mcrassembly.c

mrsassembly: mrsassembly.c

	gcc -static -o mrsassembly mrsassembly.c






